package rules
import com.example.demo.model.Bill
import com.example.demo.model.BillType
import com.example.demo.model.Renewal
import com.example.demo.rules.RenewalResponse


rule "Amount less than 3 months"
	agenda-group "renew-rules"

    when
		Integer(this < 3)
		$response: RenewalResponse(!valid, message == null)
    then  
		modify($response){setMessage("You can't renew bill for less than 3 months.");}

end

rule "Amount more than 24 months"
	agenda-group "renew-rules"

    when
		Integer(this > 24)
		$response: RenewalResponse(!valid, message == null)
    then  
		modify($response){setMessage("You can't renew bill for more than 24 months.");}

end

rule "RSD - duration of 4 months"
	agenda-group "renew-rules"

    when
        Bill(type == BillType.RSD, months() <= 4)
		$response: RenewalResponse(!valid, message == null)
    then  
		modify($response){setMessage("You can't renew RSD bill with duration of 4 months.");}

end

rule "RSD - duration of at least 42 months"
	agenda-group "renew-rules"

    when
        Bill(type == BillType.RSD, months() >= 42)
		$response: RenewalResponse(!valid, message == null)
    then  
		modify($response){setMessage("You can't renew RSD bill with duration of at least 42 months.");}

end

rule "RSD - base less than 75.000 RSD"
	agenda-group "renew-rules"

	when
        Bill(type == BillType.RSD, base < 75000)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew RSD bill with base less than 75.000 RSD.");}

end

rule "Foreign - duration of 2 months"
	agenda-group "renew-rules"

    when
        Bill(type != BillType.RSD, months() <= 2)
		$response: RenewalResponse(!valid, message == null)
    then  
		modify($response){setMessage("You can't renew foreign bill with duration of 2 months.");}

end

rule "Foreign - duration of at least 36 months"
	agenda-group "renew-rules"

    when
        Bill(type != BillType.RSD, months() >= 36)
		$response: RenewalResponse(!valid, message == null)
    then  
		modify($response){setMessage("You can't renew foreign bill with duration of at least 36 months.");}

end

rule "Foreign - base less than 750 units"
	agenda-group "renew-rules"

	when
        Bill(type != BillType.RSD, base < 750)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew foreign bill with base less than 750 currency units.");}

end

rule "Maximum renewal amount is 18 months pt1"
	agenda-group "renew-rules"

	when
        Integer(this > 18)
        Bill(type == BillType.RSD, base < 250000)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 18 months.");}

end

rule "Maximum renewal amount is 18 months pt2"
	agenda-group "renew-rules"

	when
        Integer(this > 18)
        Bill(type != BillType.RSD, base < 2500)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 18 months.");}

end

rule "Maximum renewal amount is 18 months pt3"
	agenda-group "renew-rules"

	when
        Integer(this > 18)
		Bill($renewals: renewals)
        Number(intValue >= 1) from accumulate(
        	Renewal($r: this) from $renewals,
        	count($r)
        )
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 18 months.");}

end

rule "Maximum renewal amount is 12 months pt1"
	agenda-group "renew-rules"

	when
        Integer(this > 12)
        Bill(type == BillType.RSD, base < 200000)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 12 months.");}

end

rule "Maximum renewal amount is 12 months pt2"
	agenda-group "renew-rules"

	when
        Integer(this > 12)
        Bill(type != BillType.RSD, base < 2000)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 12 months.");}

end

rule "Maximum renewal amount is 12 months pt3"
	agenda-group "renew-rules"

	when
        Integer(this > 12)
		Bill($renewals: renewals)
        Number(intValue >= 2) from accumulate(
        	Renewal($r: this) from $renewals,
        	count($r)
        )
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 12 months.");}

end

rule "Maximum renewal amount is 9 months pt1"
	agenda-group "renew-rules"

	when
        Integer(this > 9)
        Bill(type == BillType.RSD, base < 150000)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 9 months.");}

end

rule "Maximum renewal amount is 9 months pt2"
	agenda-group "renew-rules"

	when
        Integer(this > 9)
        Bill(type != BillType.RSD, base < 1500)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 9 months.");}

end

rule "Maximum renewal amount is 9 months pt3"
	agenda-group "renew-rules"

	when
        Integer(this > 9)
		Bill($renewals: renewals)
        Number(intValue >= 3) from accumulate(
        	Renewal($r: this) from $renewals,
        	count($r)
        )
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 9 months.");}

end

rule "Maximum renewal amount is 6 months pt1"
	agenda-group "renew-rules"

	when
        Integer(this > 6)
        Bill(type == BillType.RSD, base < 100000)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 6 months.");}

end

rule "Maximum renewal amount is 6 months pt2"
	agenda-group "renew-rules"

	when
        Integer(this > 6)
        Bill(type != BillType.RSD, base < 1000)
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 6 months.");}

end

rule "Maximum renewal amount is 6 months pt3"
	agenda-group "renew-rules"

	when
        Integer(this > 6)
		Bill($renewals: renewals)
        Number(intValue >= 4) from accumulate(
        	Renewal($r: this) from $renewals,
        	count($r)
        )
		$response: RenewalResponse(!valid, message == null)
	then
		modify($response){setMessage("You can't renew bill for more than 6 months.");}

end

rule "Valid params"
	agenda-group "renew-rules"

    when
		$response: RenewalResponse(!valid, message == null)
    then    
		modify($response){setValid(true)}

end

